### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by thdxr** [Vonmo/rocker#1]
I've attempted to import this library in Elixir and it says the `:rocksdb` module isn't available.  Have you gotten this working?

**Comment by thdxr** [comment]
Thanks for the fast response! I didn't notice the examples folder - that fixed it for me

**Comment by thdxr** [comment]
Got everything working, curious if you're planning on implementing the backup and delete range functionality

https://github.com/facebook/rocksdb/wiki/DeleteRange
https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F

**Comment by Elzor** [comment]
I've created #2 issue to support backup api. 
DeleteRange will be supported after implementation in rust-rocksdb #3
