### ISSUE TITLE
Multi get requiring strings

### ISSUE THREAD

**Issue by trashhalo** [Vonmo/rocker#12]
I'm having an issue with multi get where if I hand it an array of keys that are binary generated from term to binary. It responds "bad argument". It seems to work with string keys only. Is that expected?

**Comment by trashhalo** [comment]
I'm wondering if it has to do with this line: 
https://github.com/Vonmo/rocker/blob/master/crates%2Frocker%2Fsrc%2Fnif.rs#L621

**Comment by trashhalo** [comment]
The workaround I have found is I created a column family and all the _cf versions work with binary keys.

**Comment by Elzor** [comment]
Fixed in
https://github.com/Vonmo/rocker/releases/tag/v8.10.0_1
@trashhalo Thanks for the information and your attention
