### ISSUE TITLE
Update to latest rustler and rust-rocksdb

### ISSUE THREAD

**Issue by vihu** [Vonmo/rocker#4]
It would be nice if rocker updated to use the latest [rocks](https://github.com/rust-rocksdb/rust-rocksdb) and latest [rustler](https://github.com/rusterlium/rustler). Newer rocks has a more complete feature set and newer rustler has a much improved nif instantiation and type system largely driven by helpful macros.

As a potential step forward, I have a draft PR on my fork [here](https://github.com/vihu/rocker/pull/1) which gets it pretty close I think. There are still some liftetime issue I've been struggling with, I'm not a veteran rust dev :) so could use some assistance there.

**Comment by vans163** [comment]
Nice progress but its a hard error, this would be nice to have as unordered concurrent writes will be supported.
